name: derejacom
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.4
  flutter_svg: ^1.0.3
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  get_it: ^7.6.8
  fluttertoast: ^8.0.9
  provider: ^6.0.2
  intl: ^0.19.0
  quickalert: ^1.1.0
  qr_code_scanner_plus: ^2.0.6
  camera: ^0.10.0+3
  shimmer: ^3.0.0
  iconsax: ^0.0.8
  jwt_decoder: ^2.0.1
  flutter_cache_manager: ^3.3.1
  pdfx: ^2.8.0
  internet_file: ^1.2.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/DerejaIconV1.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.svg
    - assets/dereja_phone_p610yg.png
    - assets/logopng.png
    - assets/banner.png
    - assets/down5.png
    - assets/DefaultImg.jpg
    - assets/icon/icon.png
    - assets/logo_kl0fke.png
    - assets/dereja.png
    - assets/mastercard.jpg
    - assets/mcf.jpg
    - assets/expowhite-removebg-preview.png
    - assets/DerejaIconV1.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
      # - family: Raleway
      #   fonts:
      #     - asset: assets/fonts/Raleway-Regular.ttf
      #     - asset: assets/fonts/Raleway-Bold.ttf
      #       weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
